using System;
using System.Collections.Generic;

namespace RhinoMCPPlugin.Forsk
{
    /// <summary>
    /// Every user-facing string of the v3 window, in one list keyed by action
    /// id. An action's label is its id; its reason is id + ".reason". Labels
    /// are English. A Norwegian list can later sit beside this one.
    /// </summary>
    public static class ForskText
    {
        static readonly Dictionary<string, string> Strings = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            // Actions: label, then the slot 1 reason where the action can be slot 1.
            ["file.import"] = "Import a plan",
            ["file.import.reason"] = "Nothing is in this file yet.",
            ["file.import.noplan"] = "There is no plan in this file yet.",
            ["file.use_curves"] = "Use these curves as the plan",
            ["file.use_curves.reason"] = "There is geometry here that Forsk did not make.",
            ["file.use_curves.ask"] = "Select the curves that are the walls, then click Use these curves as the plan again.",
            ["file.scale"] = "Set scale",
            ["file.scale.reason"] = "The scale is not confirmed.",
            ["plan.show"] = "Show 2D",
            ["plan.hide"] = "Hide 2D",
            ["file.generate"] = "Generate 3D",
            ["file.generate.reason"] = "The plan is 2D. Scale is settled.",
            ["file.rebuild"] = "Rebuild",
            ["file.rebuild.reason"] = "The model is only partly built.",
            ["file.print"] = "Print PDF",
            ["file.print.reason"] = "A 3D model is in the file.",
            ["file.print.stale"] = "Sheets are older than the model.",
            ["file.print.map"] = "The sheet leaves the map off.",
            ["file.check"] = "Check the plan",
            ["file.sample"] = "Open sample house",
            ["file.draw"] = "Trace walls",
            ["help.card"] = "What can I do here?",
            ["daylight.rooms"] = "Make rooms",
            ["daylight.window"] = "Add a window",
            ["daylight.window.ask"] = "add a window",
            ["daylight.run"] = "Daylight",
            ["daylight.again"] = "Run daylight again",
            ["daylight.again.reason"] = "The map is out of date.",
            ["daylight.hide"] = "Hide map",
            ["daylight.show"] = "Show map",
            ["daylight.room"] = "Daylight for this room",
            ["daylight.quality"] = "Daylight quality",
            ["daylight.quality.ask"] = "Daylight quality on this Mac. Each step up uses a grid four times as fine and takes longer.",
            ["daylight.quality.now"] = "Now: {quality}.",
            ["daylight.quality.low"] = "Low",
            ["daylight.quality.medium"] = "Medium",
            ["daylight.quality.high"] = "High",
            // Settings → Grok API key: the user's own key, kept in ~/.forsk/grok.env. Only its last four characters show.
            ["grok.key"] = "Grok API key",
            ["grok.key.ask"] = "Your own xAI Grok API key for chat. It stays on this Mac.",
            ["grok.key.field"] = "Key",
            ["grok.key.none"] = "No key is set. Get one at https://console.x.ai.",
            ["grok.key.set"] = "A key ending in {tail} is set. Get a new one at https://console.x.ai.",
            ["grok.key.saved"] = "Grok key saved",
            ["grok.key.removed"] = "Grok key removed",
            ["grok.key.failed"] = "Grok key not saved: {reason}",
            ["grok.key.empty"] = "Paste a key first.",
            ["grok.key.spaces"] = "A key has no spaces. Paste it again.",
            ["grok.key.missing"] = "Chat needs your own Grok API key. Paste it below.",
            ["grok.key.where"] = "Chat needs your own Grok API key: Settings → Grok API key. Get one at https://console.x.ai.",
            // Settings → Set up Forsk: chat's key and daylight's uv, each with its state and one action.
            // Settings → Update available: a newer Forsk is on forsk.app. Rhino 7 doesn't say so itself.
            ["update.available"] = "Update available",
            ["update.row"] = "Update available: Forsk {version}",
            ["update.ask"] = "Forsk {version} is available. You have {current}.",
            ["update.step.pm"] = "Package Manager: Installed → forsk → pick {version} under Version → Install, then Apply.",
            ["update.step.restart"] = "Then quit and reopen Rhino 7.",
            ["update.note"] = "Installed from Food4Rhino? Download the new .macrhi there and double-click it.",
            ["update.open"] = "Update now",
            ["update.confirm.title"] = "Update Forsk",
            ["update.confirm"] = "Forsk updates the next time Rhino 7 starts. Rhino doesn't restart by itself: in Package Manager click Install, then Apply, then quit Rhino 7 and open it again.\n\nSave your work before you quit.",
            ["update.confirm.unsaved"] = "{file} has unsaved changes. Save it before you quit Rhino 7.",
            // What's new: once, the first time Forsk opens on a new version. Items come from whats_new.json.
            ["whatsnew.ask"] = "What's new in Forsk {version}",
            ["whatsnew.note"] = "Try them now. Something odd? Tell me here in chat.",
            ["whatsnew.done"] = "Got it",
            ["update.howto"] = "How to update",
            ["forsk.setup"] = "Set up Forsk",
            ["setup.ask"] = "Set up Forsk on this Mac. Each part works on its own.",
            ["setup.note"] = "Chat uses your own xAI Grok key from https://console.x.ai. Set up downloads uv and Python once (about 40 MB) for daylight and AI detection. Connect links this Mac to your forsk.app account; it is optional.",
            ["setup.guide"] = "Set up chat, daylight and AI detection",
            ["setup.needed"] = "Daylight and AI detection need a one-time setup. Click Set up below.",
            ["setup.where"] = "a one-time setup: Settings → Set up Forsk",
            ["setup.chat"] = "Chat",
            ["setup.chat.ready"] = "Ready · key ending in {tail}",
            ["setup.chat.needs"] = "Needs your Grok key",
            ["setup.tools"] = "Daylight & AI detection",
            ["setup.ready"] = "Ready",
            ["setup.tools.none"] = "Not set up",
            ["setup.tools.running"] = "Setting up… {step}",
            ["setup.tools.failed"] = "Failed: {reason}",
            ["setup.uv"] = "Set up",
            ["setup.account"] = "Account",
            ["setup.account.none"] = "Not connected",
            ["setup.account.waiting"] = "Code {code} · confirm it in your browser",
            ["setup.account.connected"] = "Connected as {email}",
            ["setup.account.failed"] = "Not connected: {reason}",
            ["setup.account.connect"] = "Connect",
            ["setup.account.again"] = "Connect again",
            ["setup.account.disconnect"] = "Disconnect",
            ["setup.account.offline"] = "no internet connection, try again when online.",
            ["setup.account.expired"] = "the code expired, click Connect again.",
            ["setup.uv.again"] = "Try again",
            ["setup.key.add"] = "Add Grok key",
            ["setup.key.change"] = "Change Grok key",
            ["setup.key.get"] = "Get a key",
            ["setup.step.download"] = "Downloading uv",
            ["setup.step.check"] = "Checking the download",
            ["setup.step.unpack"] = "Unpacking uv",
            ["setup.step.run"] = "Checking uv runs",
            ["setup.step.python"] = "Installing Python, about a minute",
            ["setup.fail.offline"] = "No internet connection: try again when online.",
            ["setup.fail.timeout"] = "The download took over {s} s: try again on a faster connection.",
            ["setup.fail.http"] = "The uv download failed (HTTP {code}): try again later.",
            ["setup.fail.shafile"] = "The uv checksum could not be read: try again.",
            ["setup.fail.checksum"] = "The download did not match its checksum: try again.",
            ["setup.fail.arch"] = "This Mac's processor ({machine}) has no uv build.",
            ["setup.fail.unpack"] = "Could not unpack uv: {reason}",
            ["setup.fail.run"] = "uv did not run on this Mac: {reason}",
            ["setup.fail.python"] = "Python did not install: {reason}",
            ["section.add"] = "Add a section",
            ["section.room"] = "Section through this room",
            ["room.push_pull"] = "Push or pull a side",
            ["room.draw"] = "Draw area",
            ["room.redraw"] = "Redraw area",
            ["room.push_pull.prefill"] = "Push the north side of this room {n} mm out",
            ["room.set_type"] = "Set room type",
            ["room.set_type.reason"] = "This room has no type yet.",
            ["room.set_type.prefill"] = "Change room type to: ",
            ["room.set_type.prefill.nb"] = "Endre romtype til: ",
            ["room.push_pull.prefill.nb"] = "Skyv nordsiden av rommet {n} mm ut",
            ["section.remove"] = "Remove a section",
            ["opening.move"] = "Move",
            ["opening.move.prefill"] = "Move this {kind} {n} mm along the wall",
            ["opening.move.prefill.nb"] = "Flytt {kind} {n} mm langs veggen",
            ["opening.resize"] = "Resize",
            ["opening.resize.prefill"] = "Make this {kind} {n} mm wide",
            ["opening.resize.prefill.nb"] = "Sett bredden på {kind} til {n} mm",
            ["opening.type"] = "Change type",
            ["opening.delete"] = "Delete",
            ["opening.add_door"] = "Add a door here",
            ["opening.add_door.ask"] = "add a door on this wall",
            ["wall.move"] = "Move",
            ["wall.move.reason"] = "The click selects the whole wall record.",
            ["wall.move.reason.one"] = "The click selects one wall.",
            ["wall.drag.not"] = "Not moved: the wall was not dragged.",
            ["wall.drag.not.nb"] = "Ikke flyttet: veggen ble ikke dratt.",
            ["wall.drag.many"] = "Drag works on one wall. Split walls for picking first.",
            ["wall.drag.many.nb"] = "Du kan dra én vegg. Del veggene for plukking først.",
            ["wall.drag.curved"] = "A curved wall can't be dragged; it stays one record.",
            ["wall.drag.curved.nb"] = "En buet vegg kan ikke dras. Den blir stående som én vegg.",
            ["wall.drag.dim.out"] = "{n} mm out",
            ["wall.drag.dim.out.nb"] = "{n} mm ut",
            ["wall.drag.dim.in"] = "{n} mm in",
            ["wall.drag.dim.in.nb"] = "{n} mm inn",
            ["wall.drag.dim.plus"] = "+{n} mm",
            ["wall.drag.dim.plus.nb"] = "+{n} mm",
            ["wall.drag.dim.minus"] = "-{n} mm",
            ["wall.drag.dim.minus.nb"] = "-{n} mm",
            ["wall.drag.dim.zero"] = "0 mm",
            ["wall.drag.dim.zero.nb"] = "0 mm",
            ["wall.drag.out"] = "out",
            ["wall.drag.out.nb"] = "ut",
            ["wall.drag.in"] = "in",
            ["wall.drag.in.nb"] = "inn",
            ["wall.drag.side.north"] = "North wall",
            ["wall.drag.side.north.nb"] = "Nordveggen",
            ["wall.drag.side.south"] = "South wall",
            ["wall.drag.side.south.nb"] = "Sørveggen",
            ["wall.drag.side.east"] = "East wall",
            ["wall.drag.side.east.nb"] = "Østveggen",
            ["wall.drag.side.west"] = "West wall",
            ["wall.drag.side.west.nb"] = "Vestveggen",
            ["wall.drag.receipt.outer"] = "{wall} moved {n} mm {way}",
            ["wall.drag.receipt.outer.nb"] = "{wall} flyttet {n} mm {way}",
            ["wall.drag.receipt.inner"] = "{wall} moved {n} mm {toward}",
            ["wall.drag.receipt.inner.nb"] = "{wall} flyttet {n} mm mot {toward}",
            ["wall.drag.followed.one"] = "; 1 wall followed",
            ["wall.drag.followed.one.nb"] = "; 1 vegg fulgte",
            ["wall.drag.followed"] = "; {n} walls followed",
            ["wall.drag.followed.nb"] = "; {n} vegger fulgte",
            ["wall.drag.pick"] = "Click the wall to drag.",
            ["wall.drag.pick.nb"] = "Klikk veggen som skal dras.",
            ["wall.drag.cancel"] = "Cancelled.",
            ["wall.drag.cancel.nb"] = "Avbrutt.",
            ["wall.drag"] = "Drag a face",
            ["wall.drag.nb"] = "Dra en flate",
            ["wall.drag.prompt"] = "Drag the wall in the view, or type a distance. Click or Enter places it. Esc cancels.",
            ["wall.drag.prompt.nb"] = "Dra veggen i visningen, eller skriv en avstand. Klikk eller Enter plasserer den. Esc avbryter.",
            ["wall.face.pick"] = "Click a face of the wall: an end changes its length, a side moves it or changes its thickness.",
            ["wall.face.pick.nb"] = "Klikk en flate på veggen: en ende endrer lengden, en side flytter den eller endrer tykkelsen.",
            ["wall.face.pick.side"] = "Click the side of the wall to move.",
            ["wall.face.pick.side.nb"] = "Klikk siden av veggen som skal flyttes.",
            ["wall.face.prompt.end"] = "Drag the end, or type how much longer (-800 shortens). Click or Enter places it. Esc cancels.",
            ["wall.face.prompt.end.nb"] = "Dra enden, eller skriv hvor mye lenger (-800 forkorter). Klikk eller Enter plasserer den. Esc avbryter.",
            ["wall.face.prompt.side"] = "Drag the face, or type a distance. Thickness moves this face alone; then type the new thickness. Click or Enter places it. Esc cancels.",
            ["wall.face.prompt.side.nb"] = "Dra flaten, eller skriv en avstand. Tykkelse flytter bare denne flaten; skriv da ny tykkelse. Klikk eller Enter plasserer den. Esc avbryter.",
            ["wall.face.dim.longer"] = "+{n} mm, {len} mm long",
            ["wall.face.dim.longer.nb"] = "+{n} mm, {len} mm lang",
            ["wall.face.dim.shorter"] = "-{n} mm, {len} mm long",
            ["wall.face.dim.shorter.nb"] = "-{n} mm, {len} mm lang",
            ["wall.face.dim.thick"] = "{n} mm thick",
            ["wall.face.dim.thick.nb"] = "{n} mm tykk",
            ["wall.face.not"] = "Not changed: the face was not dragged.",
            ["wall.face.not.nb"] = "Ikke endret: flaten ble ikke dratt.",
            ["wall.split"] = "Split walls for picking",
            ["wall.merge"] = "Merge walls",
            ["wall.delete"] = "Delete",
            ["wall.delete.ask"] = "Which wall run goes? A click selects the whole wall record.",
            ["wall.delete.inner"] = "For an inner wall, say it: “delete the wall at 4000, 2500”.",
            ["exist.mark"] = "Treat this as the existing house?",
            ["wall.draw"] = "Draw wall",
            ["stair.draw"] = "Draw stair",
            ["stair.add"] = "Add stair",
            ["stair.edit"] = "Edit stair",
            ["stair.delete"] = "Delete stair",
            ["edit.undo"] = "Undo",
            ["ink.set"] = "Ink",
            ["meta.title"] = "Project info",
            ["meta.title.nb"] = "Prosjektinfo",
            ["bridge.start"] = "Start bridge",
            ["print.one"] = "Print one sheet",
            ["print.pages"] = "Choose sheets",
            ["export.dwg"] = "Export DWG",
            ["export.ifc"] = "Export IFC",
            ["view.export"] = "Export viewport",
            ["view.export.reason"] = "this view is a render",
            ["view.exported"] = "Saved {file}, {width} × {height} px.",
            ["view.exported.reveal"] = "Show in Finder",
            ["export.csv"] = "Export CSV",
            ["export.csv.nb"] = "Eksporter CSV",
            ["detail.add"] = "Add detail",
            ["detail.add.nb"] = "Legg til detalj",
            ["detail.list"] = "Your details",
            ["detail.list.ask"] = "Details you added. Untick one and Save to remove it.",
            ["detail.plan"] = "plan",
            ["detail.elevation"] = "elevation",
            ["detail.section"] = "section",
            ["word.remove_all"] = "Remove all",
            ["word.remove"] = "Remove",
            ["takeoff"] = "Takeoff",
            ["print.clear"] = "Clear the layouts",
            ["sheets.clear"] = "Clear the sheet cache",
            ["rooms.list"] = "List rooms",
            ["whats.new.show"] = "Release notes",
            ["room.inside"] = "Interior render",
            ["room.inside.ask"] = "Which way should the camera look?",
            ["room.inside.north"] = "North",
            ["room.inside.east"] = "East",
            ["room.inside.south"] = "South",
            ["room.inside.west"] = "West",
            ["room.inside.pick"] = "Click a room's floor for its interior render.",
            ["room.inside.nopick"] = "No room clicked. Choose Interior render again when you are ready.",
            ["room.inside.held"] = "Looking {way}. Confirm saves it as a named view.",
            ["view.exterior"] = "Exterior render",
            ["view.exterior.ask"] = "Which side should the camera stand on?",
            ["view.exterior.held"] = "From the {way}. Confirm saves it as a named view.",
            ["furniture.add"] = "Add furniture",
            ["furniture.furnish"] = "Furnish rooms",
            ["furniture.add.ask"] = "Add which piece, and where?",
            ["furniture.add.item"] = "Piece",
            ["furniture.add.room"] = "Room",
            ["furniture.add.picked"] = "The picked room",
            ["furniture.add.note"] = "Forsk stands it against the longest free wall, or in the middle for tables and chairs.",
            ["area.stats"] = "Area summary",
            ["analysis.add"] = "Add to analysis set",
            ["option.save"] = "Save as option",
            ["option.compare"] = "Compare options",
            ["option.compare.ask"] = "Compare which option with the model now?",
            ["option.restore"] = "Restore an option",
            ["option.restore.ask"] = "Restore which option? The model goes back to it; one Undo brings it back.",
            ["option.delete"] = "Delete an option",
            ["option.delete.ask"] = "Delete which option? Its file goes; the model stays.",
            ["tool.restore_option"] = "Option",
            ["tool.rename_option"] = "Option",
            ["tool.delete_option"] = "Option",
            ["option.compare.title"] = "Option {name} against now: {summary}.",
            ["option.row"] = "{label}: A {option} · now {now}",
            ["option.name"] = "Option {name}",
            ["analysis.added"] = "{name} is in the analysis set. Print it from the Analyses menu.",
            ["analysis.print"] = "Print analysis set",
            ["analysis.print.ask"] = "Analyses in the set. It prints as its own PDF.",
            ["analysis.saved"] = "Analysis set: {names}.",
            ["analysis.set.empty"] = "Nothing in the analysis set yet. Tick an analysis first.",
            ["analysis.check"] = "{name}: {about}",
            ["analysis.about.daylight"] = "the daylight factor in each room, from the last run",
            ["analysis.about.areas"] = "net, gross and usable area by floor and use",
            ["area.summary.note"] = "Estimate. Not measured to NS 3940.",

            // One-time cards: the question, then the pills.
            ["opening.type.ask"] = "Change to:",
            ["stair.edit.ask"] = "Stair sizes. The steps stay equal: their count follows the height.",
            ["stair.width"] = "Width",
            ["stair.riser_max"] = "Step height, at most",
            ["stair.going"] = "Going",
            ["stair.flip"] = "Flip",
            ["stair.same"] = "Nothing changed: the sizes are the same.",
            ["opening.type.all.ask"] = "Change all windows or all doors to:",
            ["opening.type.all.door"] = "Change all doors to:",
            ["opening.type.all.window"] = "Change all windows to:",
            ["file.check.ask"] = "What the import was not sure about",
            ["wall.review.ask"] = "What followed the wall",
            ["wall.review.ask.nb"] = "Hva som fulgte veggen",
            ["wall.review.longer"] = "{wall} · {mm} mm longer",
            ["wall.review.longer.nb"] = "{wall} · {mm} mm lengre",
            ["wall.review.shorter"] = "{wall} · {mm} mm shorter",
            ["wall.review.shorter.nb"] = "{wall} · {mm} mm kortere",
            ["wall.review.row"] = "{wall}",
            ["wall.review.row.nb"] = "{wall}",
            ["ink.set.ask"] = "Ink for the next Print. Sheets already drawn keep theirs until then.",
            ["ink.set.now"] = "Now: {ink}.",
            ["ink.default"] = "Default",
            ["ink.grey"] = "Grey",
            ["ink.hatch"] = "Hatch",
            ["meta.title.ask"] = "Project info for the title blocks.",
            ["meta.title.ask.nb"] = "Prosjektinfo til tegningshodene.",
            ["meta.title.first"] = "Project info for the title blocks. Asked once.",
            ["meta.title.first.nb"] = "Prosjektinfo til tegningshodene. Spørres én gang.",
            ["meta.save.print"] = "Save and print",
            ["meta.save.print.nb"] = "Lagre og skriv ut",
            ["meta.save.export"] = "Save and export",
            ["meta.save.export.nb"] = "Lagre og eksporter",
            ["meta.skip.print"] = "Print without",
            ["meta.skip.print.nb"] = "Skriv ut uten",
            ["meta.skip.export"] = "Export without",
            ["meta.skip.export.nb"] = "Eksporter uten",
            ["print.one.ask"] = "Which sheet?",
            ["print.pages.ask"] = "Sheets in the set",
            ["print.pages.scale"] = "Scale",
            ["print.pages.fit"] = "Scale picked to fit · A3",
            ["takeoff.ask"] = "Takeoff",
            ["takeoff.note"] = "Every figure is approx., from the model. Wall area is net of openings, one side.",
            ["sheet.section"] = "Section {letter}",
            ["print.clear.ask"] = "Clear the Forsk layouts and their drawings? The model stays.",
            ["sheets.clear.ask"] = "Clear the sheet cache on S-PLAN and S-ELEV? Print does not use it.",
            ["rooms.list.ask"] = "Rooms in this file",
            ["section.remove.ask"] = "Which section goes?",
            ["section.remove.all"] = "All sections",
            ["pdf.page.ask"] = "{file} has {n} pages. Which is the plan?",
            ["pdf.page.pill"] = "Page {n}",
            ["pdf.page.more"] = "Showing the first {n} pages.",
            // UX.2: the guided AI detection flow (ForskImportGuide).
            ["guide.title"] = "Import a plan with AI detection",
            ["guide.step.file"] = "Choose file",
            ["guide.step.scale"] = "Set scale",
            ["guide.step.review"] = "Review",
            ["guide.step.generate"] = "Generate 3D",
            ["guide.file.how"] = "A PDF from your CAD program, a scan or photo of a plan (PNG or JPEG), or a DXF. AI detection finds the walls, doors, windows and rooms.",
            ["guide.file.replaces"] = "This file already has a plan. The new one replaces it, and Undo brings the old one back.",
            ["guide.file.undone"] = "The import was undone. Choose a file to start again.",
            ["guide.file.reading"] = "Reading {file}…",
            ["guide.read.cancelled"] = "Import cancelled. Nothing was added.",
            ["guide.file.read.pdf"] = "{file}, read from the PDF's own lines",
            ["guide.file.read.scan"] = "{file}, read as a scan by the AI detection model",
            ["guide.file.read.dxf"] = "{file}, read from the DXF's layers",
            ["guide.failed"] = "AI detection could not read {file}",
            ["guide.failed.unknown"] = "Nothing was imported. Try another file: a PDF exported from CAD reads best.",
            ["guide.setup"] = "AI detection needs a one-time setup first. Click Set up on the card below, then choose the file again.",
            ["guide.units"] = "This Rhino file is not in millimetres. Start a new file from a Millimeters template, then import again.",
            ["guide.scale.unsure"] = "The plan's scale was not found{ratio}. Pick two points on a length you know, like a dimension line, then type the real length.",
            ["guide.scale.assumed"] = " (it assumes {ratio})",
            ["guide.scale.detected"] = "{ratio} was read from the plan. Check it with two points on a length you know, or keep it.",
            ["guide.scale.user"] = "Set from two points",
            ["guide.scale.kept"] = "Kept {ratio} from the plan",
            ["guide.scale.skipped"] = "Skipped. Set scale stays in the bar",
            ["guide.scale.dxf"] = "From the DXF's units",
            ["guide.found"] = "AI detection found {walls}, {doors} and {windows}.",
            ["guide.review.ask"] = "Compare it with the faded drawing under it. These were unsure. Fix them in Rhino or ask in chat, then click Looks right.",
            ["guide.review.none"] = "Compare it with the faded drawing under it. Nothing looked unsure.",
            ["guide.review.more"] = "and {n} more",
            ["guide.generate.ask"] = "Turn the plan into 3D walls, doors, windows and rooms.",
            ["guide.licence"] = "Scans are read by the CubiCasa5k model, licensed CC BY-NC 4.0 for non-commercial use.",
            ["guide.pill.choose"] = "Choose file",
            ["guide.pill.another"] = "Choose another file",
            ["guide.pill.scale"] = "Set scale",
            ["guide.pill.keep"] = "Keep {ratio}",
            ["guide.pill.skip"] = "Skip for now",
            ["guide.pill.looks"] = "Looks right",
            ["guide.pill.generate"] = "Generate 3D",
            ["guide.pill.later"] = "Later",
            ["guide.receipt.generate"] = "Plan imported with AI detection · generating 3D",
            ["guide.receipt.later"] = "Plan imported with AI detection. Generate 3D is in the bar when you're ready.",
            ["guide.progress.start"] = "AI detection: opening {file}",
            ["guide.progress.pdf"] = "AI detection: reading the PDF's own lines",
            ["guide.progress.scan"] = "AI detection: reading the plan as a scan (the first time takes a few minutes)",
            ["guide.progress.place"] = "AI detection: drawing walls, doors, windows and rooms",
            ["guide.progress.dxf"] = "Reading the DXF",
            ["guide.subject"] = "AI detection",
            ["word.done"] = "Done",
            ["analyser.title"] = "Analyses",
            ["analyser.ask"] = "Analyses for this file.",
            ["analyser.none"] = "Daylight and areas need walls and rooms. Generate 3D first.",
            // AN.1 and AN.2: the menu's rows and Live switches.
            ["analysis.daylight"] = "Daylight",
            ["analysis.areas"] = "Areas",
            ["analysis.row"] = "{name}: {last}",
            ["analysis.never"] = "not run yet",
            ["analysis.live"] = "{name} live",
            ["analysis.live.note"] = "Live analyses run again after every wall or opening edit, and the edit says what changed. Daylight live uses the Low grid.",
            ["word.save"] = "Save",
            ["word.confirm"] = "Confirm",
            ["word.unchanged"] = "unchanged",
            ["opening.type.now"] = "Now: {type}.",
            ["print.pages.paper"] = "Paper",
            ["meta.logo.choose"] = "Choose logo",
            ["meta.logo.change"] = "Change logo",
            ["meta.logo.remove"] = "Remove logo",
            ["word.print"] = "Print",
            ["word.reset"] = "Reset",

            // Words in a prefilled sentence.
            ["word.door"] = "door",
            ["word.window"] = "window",
            ["word.door.nb"] = "døra",
            ["word.window.nb"] = "vinduet",
            ["word.north"] = "North",
            ["word.south"] = "South",
            ["word.east"] = "East",
            ["word.west"] = "West",
            ["word.cancel"] = "Cancel",
            ["compass.north"] = "north",
            ["compass.north.nb"] = "nord",
            ["compass.south"] = "south",
            ["compass.south.nb"] = "sør",
            ["compass.east"] = "east",
            ["compass.east.nb"] = "øst",
            ["compass.west"] = "west",
            ["compass.west.nb"] = "vest",

            // The pick line (ForskPick): what is selected, in words.
            ["pick.none"] = "Click something in the model.",
            ["pick.none.nb"] = "Klikk noe i modellen.",
            ["pick.wall"] = "Wall {id}",
            ["pick.wall.nb"] = "Vegg {id}",
            ["pick.wall.at"] = "Wall at {at}",
            ["pick.wall.at.nb"] = "Vegg ved {at}",
            ["pick.wall.whole"] = "Wall {id} · {n} runs",
            ["pick.wall.whole.nb"] = "Vegg {id} · {n} deler",
            ["pick.room"] = "Room",
            ["pick.room.nb"] = "Rom",
            ["pick.door"] = "Door",
            ["pick.door.nb"] = "Dør",
            ["pick.window"] = "Window",
            ["pick.window.nb"] = "Vindu",
            ["pick.opening"] = "Opening",
            ["pick.opening.nb"] = "Åpning",
            ["pick.object"] = "1 object",
            ["pick.object.nb"] = "1 objekt",
            ["pick.walls"] = "{n} walls",
            ["pick.walls.nb"] = "{n} vegger",
            ["pick.rooms"] = "{n} rooms · {area}",
            ["pick.rooms.nb"] = "{n} rom · {area}",
            ["pick.doors"] = "{n} doors",
            ["pick.doors.nb"] = "{n} dører",
            ["pick.windows"] = "{n} windows",
            ["pick.windows.nb"] = "{n} vinduer",
            ["pick.openings"] = "{n} openings",
            ["pick.openings.nb"] = "{n} åpninger",
            ["pick.mix.wall"] = "1 wall",
            ["pick.mix.wall.nb"] = "1 vegg",
            ["pick.mix.door"] = "1 door",
            ["pick.mix.door.nb"] = "1 dør",
            ["pick.mix.window"] = "1 window",
            ["pick.mix.window.nb"] = "1 vindu",
            ["pick.mix.opening"] = "1 opening",
            ["pick.mix.opening.nb"] = "1 åpning",
            ["pick.stairs"] = "{n} stairs",
            ["pick.stairs.nb"] = "{n} trapper",
            ["pick.objects"] = "{n} objects",
            ["pick.objects.nb"] = "{n} objekter",

            // A viewport pick, mirrored as one line in the thread. Rhino takes the keyboard while it runs.
            ["prompt.scale"] = "Pick two points on a length you know, in the viewport. Esc cancels.",
            ["prompt.scale.length"] = "Real length between the two points",
            ["prompt.scale.set"] = "Set scale",
            ["prompt.section"] = "Pick the start of the section in the viewport, then its end. Esc cancels.",
            ["prompt.stair"] = "Click the foot of the stair in the plan, then where it ends. Type a length, or W for the width. Esc cancels.",
            ["prompt.area"] = "Click the room's corners along the walls' inner faces, or pick a closed curve you drew. Enter or C closes the area, Esc steps back.",
            ["prompt.wall"] = "Click the corners of the walls in the plan. Type a length and Enter, C closes, Enter finishes, Esc steps back. Shift turns the angle snap off.",
            ["prompt.draw"] = "Trace the walls in the viewport, on the wall layer. Enter finishes, Esc cancels.",

            // Lines in the thread.
            ["window.nofile"] = "No file open",
            ["line.reopened"] = "Reopened. The bar shows what is true for this file now.",
            ["line.busy"] = "Forsk is still working. Try again when the step line is gone.",
            ["line.thinking"] = "Thinking",
            ["line.generating"] = "Generating… step {i} of {n}",
            ["line.printing"] = "Printing… step {i} of {n}: {what}",
            ["line.running"] = "Running {what}…",
            ["line.bridge"] = "Bridge started.",
            ["line.printing.layout"] = "laying out the sheets",
            ["line.scale.cancelled"] = "Set scale cancelled.",
            ["line.scale.number"] = "Type the length in millimetres, such as 4000.",
            ["file.use_curves.done"] = "{n} curve(s) are on the wall layer now.",
            ["edit.undo.none"] = "Rhino had nothing to undo.",
            ["bridge.start.failed"] = "The bridge did not start: {why}",

            // Roles. One thread and one history; a role sharpens suggestions and tool choice.
            ["role.control"] = "Answer as",
            ["role.auto"] = "Auto",
            ["role.planner"] = "Planner",
            ["role.modeller"] = "Modeller",
            ["role.plotter"] = "Plotter",
            ["role.analyser"] = "Analyser",
            ["role.support"] = "Support",
            ["role.render"] = "Render",
            ["role.title"] = "Auto lets the router name the role for each answer. A pick stays until you choose Auto again.",
            ["support.ask"] = "Send this report?",
            ["support.send"] = "Send",
            ["support.sending"] = "Sending…",
            ["support.sending.nb"] = "Sender…",
            ["support.sent.short"] = "Sent",
            ["support.sent.short.nb"] = "Sendt",
            ["support.saved.short"] = "Saved",
            ["support.saved.short.nb"] = "Lagret",
            ["support.notsent"] = "Not sent",
            ["support.notsent.nb"] = "Ikke sendt",
            ["support.type"] = "Type",
            ["support.bug"] = "Bug",
            ["support.question"] = "Question",
            ["support.feature"] = "Feature request",
            ["support.description"] = "Description",
            ["support.email"] = "Email",
            ["support.attach"] = "Attach debug report",
            ["support.sent"] = "Sent. Reference {id} — we'll reply by email.",
            ["support.sent.nb"] = "Sendt. Referanse {id} — vi svarer på e-post.",
            ["support.sent.plain"] = "Sent. We'll reply by email.",
            ["support.sent.plain.nb"] = "Sendt. Vi svarer på e-post.",
            ["support.unavailable"] = "Couldn't reach Forsk support right now — your report is saved and will be sent later.",
            ["support.unavailable.nb"] = "Fikk ikke kontakt med Forsk support akkurat nå — rapporten er lagret og sendes senere.",
            ["support.later"] = "Support email isn't set up yet — your report is saved and will be sent later.",
            ["support.later.nb"] = "E-post til support er ikke satt opp ennå — rapporten er lagret og sendes senere.",
            ["support.failed"] = "The report didn't go through — it's saved and will be sent later.",
            ["support.failed.nb"] = "Rapporten kom ikke frem — den er lagret og sendes senere.",
            ["support.rate"] = "Too many reports just now — try again in {n} minutes.",
            ["support.rate.nb"] = "For mange rapporter akkurat nå — prøv igjen om {n} minutter.",
            ["support.rate.one"] = "Too many reports just now — try again in 1 minute.",
            ["support.rate.one.nb"] = "For mange rapporter akkurat nå — prøv igjen om 1 minutt.",
            ["support.rate.later"] = "Too many reports just now — try again in a few minutes.",
            ["support.rate.later.nb"] = "For mange rapporter akkurat nå — prøv igjen om noen minutter.",
            ["support.email.bad"] = "Type the email we should reply to.",
            ["support.email.bad.nb"] = "Skriv e-postadressen vi skal svare til.",
            ["support.message.missing"] = "Write what happened, then send.",
            ["support.message.missing.nb"] = "Skriv hva som skjedde, og send.",
            ["support.message.long"] = "That description is too long. Shorten it, then send.",
            ["support.message.long.nb"] = "Beskrivelsen er for lang. Korte den ned, og send.",
            ["support.type.bad"] = "Choose Bug, Question, or Feature request.",
            ["support.type.bad.nb"] = "Velg Bug, Question eller Feature request.",
            ["support.rejected"] = "That report couldn't be sent. Check it and try again.",
            ["support.rejected.nb"] = "Rapporten ble ikke sendt. Se over den og prøv igjen.",
            ["support.too_large"] = "That report is too large to send.",
            ["support.too_large.nb"] = "Rapporten er for stor til å sendes.",
            ["support.debug_large"] = "The debug report is too large. Untick it and send again.",
            ["support.debug_large.nb"] = "Feilsøkingsrapporten er for stor. Fjern haken og send på nytt.",

            // The bar.
            ["bar.because"] = "Suggested because",
            ["bar.help"] = "\u22ef",
            ["bar.refused"] = "{label} is no longer available here: the file changed.",

            // "What can I do here?" groups, in card order.
            ["group.start"] = "Start a project",
            ["group.model"] = "Model and edit",
            ["group.rooms"] = "Rooms",
            ["group.analyses"] = "Analyses",
            ["group.print"] = "Print and export",
            ["group.chat"] = "Chat",
            ["chat.clear"] = "Clear chat",
            ["options"] = "Options",
            ["analysis.menu"] = "Analyses menu",
            ["options.ask"] = "Options of this model, kept beside the saved file.",

            // One sentence where a neighbour would expect a dead control.
            ["hint.key"] = "Chat actions are hidden until you add your Grok API key: Settings → Grok API key.",
            ["hint.windows"] = "Daylight comes in through windows. Add a window, then run it.",
            ["hint.scale"] = "Generate waits for the scale: pick two points in the view, then type the real length.",
            ["hint.heights"] = "Generate uses the template heights. For other heights, say them: “generate with walls 2700”.",
            ["hint.units"] = "This file is not in millimetres. Forsk works in millimetres only.",

            // The one local sentence on an empty thread: it names the file state. No key needed.
            ["state.empty"] = "This file is empty.",
            ["state.foreign"] = "This file has geometry that Forsk did not make.",
            ["state.unscaled"] = "This file has an imported plan. Its scale is not confirmed.",
            ["state.plan"] = "This file has a 2D plan and no 3D model yet.",
            ["state.noplan"] = "This file has no plan yet.",
            ["state.partial"] = "This file has part of a Forsk model and no walls.",
            ["state.model"] = "This file has a Forsk 3D model.",
            ["state.units"] = "This file is not in millimetres. Switch the .3dm to millimetres, then Forsk can work on it.",

            // The status line.
            ["status.ink"] = "ink: {ink}",

            // A step whose object is not named in its message.
            ["tool.clear_generated"] = "Model",
            ["tool.floor_from_layer"] = "Floor",
            ["tool.walls_from_layer"] = "Walls",
            ["tool.roof_flat_from_walls"] = "Roof",
            ["tool.openings_from_layer"] = "Openings",
            ["tool.rooms_from_layer"] = "Rooms",
            ["tool.rooms_detect"] = "Rooms",
            ["tool.rooms_set_type"] = "Room type",
            ["tool.rooms_colors"] = "Room colours",
            ["tool.mark_as_existing"] = "Existing house",
            ["tool.plan_import"] = "Plan",
            ["tool.plan_scale"] = "Scale",
            ["tool.dxf_import"] = "DXF",
            ["tool.layout_pack"] = "Sheets",
            ["tool.export_pdf"] = "PDF",
            ["tool.print_pages"] = "Sheets",
            ["tool.takeoff"] = "Takeoff",
            ["tool.clear_layouts"] = "Layouts",
            ["tool.clear_drawings"] = "Sheet cache",
            ["tool.sheet_pack"] = "Sheet cache",
            ["tool.make2d_view"] = "Sheet cache",
            ["tool.set_project_meta"] = "Title block",
            ["tool.print_profile"] = "Ink",
            ["tool.section_add"] = "Section",
            ["tool.section_clear"] = "Section",
            ["tool.section_pick"] = "Section",
            ["tool.daylight_from_model"] = "Daylight",
            ["tool.debug_report"] = "Debug report",
            ["tool.add_opening"] = "Opening",
            ["tool.move_opening"] = "Opening",
            ["tool.set_opening"] = "Opening",
            ["tool.set_opening_type"] = "Opening",
            ["tool.delete_opening"] = "Opening",
            ["tool.move_wall"] = "Wall",
            ["tool.edit_wall_face"] = "Wall",
            ["tool.set_wall"] = "Wall",
            ["tool.delete_wall"] = "Wall",
            ["tool.add_wall"] = "Wall",
            ["tool.add_room_area"] = "Area",
            ["tool.split_walls"] = "Wall",
            ["tool.merge_walls"] = "Wall",
            ["tool.room_push_pull"] = "Room",
            ["tool.add_stair"] = "Stair",
            ["tool.edit_stair"] = "Stair",
            ["tool.delete_stair"] = "Stair",
            ["tool.add_furniture"] = "Furniture",
            ["tool.move_furniture"] = "Furniture",
            ["tool.delete_furniture"] = "Furniture",
            ["tool.furnish_room"] = "Furniture",
            ["tool.jump_inside"] = "View",
            ["tool.exterior_render"] = "View",
            ["tool.show_view"] = "View",
            ["tool.save_option"] = "Option",
            ["tool.compare_option"] = "Option",
            ["view.show"] = "Show view",
            ["saved_views.ask"] = "Rename or delete your saved views.",
            ["saved_views.note"] = "Empty a name to delete that view.",
            ["saved_views.name"] = "Name",
            ["saved_views.unchanged"] = "No saved view changed.",
            ["saved_views.open"] = "Rename or delete saved views",
            // FU.7: the two furnish layouts as ghosts, picked on a card.
            ["furnish.pick.ask"] = "Two layouts for {room}. Which one goes in?",
            ["furnish.pick.one"] = "One layout for {room}, shown in blue.",
            ["furnish.pick.usual"] = "Blue: {pieces}",
            ["furnish.pick.other"] = "Orange: {pieces}",
            ["furnish.place.usual"] = "Place blue",
            ["furnish.place.other"] = "Place orange",
            ["furnish.place.one"] = "Place it",
            ["receipt.ok"] = "done",
        };

        /// <summary>The string under a key. A missing key is a bug the registry tests catch; the key shows instead of a blank.</summary>
        public static string Get(string key)
        {
            return key != null && Strings.TryGetValue(key, out var text) ? text : key ?? "";
        }

        public static bool Has(string key)
        {
            return key != null && Strings.ContainsKey(key);
        }

        public static string Label(string actionId)
        {
            return Get(actionId);
        }

        /// <summary>A string with {name} slots filled.</summary>
        public static string Format(string key, params string[] pairs)
        {
            var text = Get(key);
            for (var i = 0; i + 1 < pairs.Length; i += 2)
                text = text.Replace("{" + pairs[i] + "}", pairs[i + 1] ?? "");
            return text;
        }

        public static IEnumerable<string> Keys => Strings.Keys;
    }
}
