using System;
using System.Collections.Generic;

namespace RhinoMCPPlugin.Forsk
{
    /// <summary>
    /// Every user-facing string of the v3 window, in one list keyed by action
    /// id. An action's label is its id; its reason is id + ".reason". Labels
    /// are English. A Norwegian list can later sit beside this one.
    /// </summary>
    public static class ForskText
    {
        static readonly Dictionary<string, string> Strings = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            // Actions: label, then the slot 1 reason where the action can be slot 1.
            ["file.import"] = "Import a plan",
            ["file.import.reason"] = "Nothing is in this file yet.",
            ["file.import.noplan"] = "There is no plan in this file yet.",
            ["file.use_curves"] = "Use these curves as the plan",
            ["file.use_curves.reason"] = "There is geometry here that Forsk did not make.",
            ["file.use_curves.ask"] = "Select the curves that are the walls, then click Use these curves as the plan again.",
            ["file.scale"] = "Set scale",
            ["file.scale.reason"] = "The scale is not confirmed.",
            ["plan.show"] = "Show 2D",
            ["plan.hide"] = "Hide 2D",
            ["file.generate"] = "Generate 3D",
            ["file.generate.reason"] = "The plan is 2D. Scale is settled.",
            ["file.rebuild"] = "Rebuild",
            ["file.rebuild.reason"] = "The model is only partly built.",
            ["file.print"] = "Print PDF",
            ["file.print.reason"] = "A 3D model is in the file.",
            ["file.print.stale"] = "Sheets are older than the model.",
            ["file.print.map"] = "The sheet leaves the map off.",
            ["file.check"] = "Check the plan",
            ["file.sample"] = "Open sample house",
            ["file.draw"] = "Trace walls",
            ["help.card"] = "What can I do here?",
            ["daylight.rooms"] = "Make rooms",
            ["daylight.window"] = "Add a window",
            ["daylight.window.ask"] = "add a window",
            ["daylight.run"] = "Daylight",
            ["daylight.again"] = "Run daylight again",
            ["daylight.again.reason"] = "The map is out of date.",
            ["daylight.hide"] = "Hide map",
            ["daylight.show"] = "Show map",
            ["daylight.room"] = "Daylight for this room",
            ["section.add"] = "Add a section",
            ["section.room"] = "Section through this room",
            ["room.push_pull"] = "Push or pull a side",
            ["room.push_pull.prefill"] = "Push the north side of this room {n} mm out",
            ["room.push_pull.prefill.nb"] = "Skyv nordsiden av rommet {n} mm ut",
            ["section.remove"] = "Remove a section",
            ["opening.move"] = "Move",
            ["opening.move.prefill"] = "Move this {kind} {n} mm along the wall",
            ["opening.move.prefill.nb"] = "Flytt {kind} {n} mm langs veggen",
            ["opening.resize"] = "Resize",
            ["opening.resize.prefill"] = "Make this {kind} {n} mm wide",
            ["opening.resize.prefill.nb"] = "Sett bredden på {kind} til {n} mm",
            ["opening.type"] = "Change type",
            ["opening.delete"] = "Delete",
            ["opening.add_door"] = "Add a door here",
            ["opening.add_door.ask"] = "add a door on this wall",
            ["wall.move"] = "Move",
            ["wall.move.prefill"] = "Move the north wall {n} mm north",
            ["wall.move.prefill.nb"] = "Flytt veggen i nord {n} mm mot nord",
            ["wall.move.reason"] = "The click selects the whole wall record.",
            ["wall.move.reason.one"] = "The click selects one wall.",
            ["wall.move.prefill.run"] = "Move {wall} {n} mm {toward}",
            ["wall.move.prefill.run.nb"] = "Flytt {wall} {n} mm mot {toward}",
            ["wall.drag.not"] = "Not moved: the wall was not dragged.",
            ["wall.drag.not.nb"] = "Ikke flyttet: veggen ble ikke dratt.",
            ["wall.drag.many"] = "Drag works on one wall. Split walls for picking first.",
            ["wall.drag.many.nb"] = "Du kan dra én vegg. Del veggene for plukking først.",
            ["wall.drag.curved"] = "A curved wall can't be dragged; it stays one record.",
            ["wall.drag.curved.nb"] = "En buet vegg kan ikke dras. Den blir stående som én vegg.",
            ["wall.drag.dim.out"] = "{n} mm out",
            ["wall.drag.dim.out.nb"] = "{n} mm ut",
            ["wall.drag.dim.in"] = "{n} mm in",
            ["wall.drag.dim.in.nb"] = "{n} mm inn",
            ["wall.drag.dim.plus"] = "+{n} mm",
            ["wall.drag.dim.plus.nb"] = "+{n} mm",
            ["wall.drag.dim.minus"] = "-{n} mm",
            ["wall.drag.dim.minus.nb"] = "-{n} mm",
            ["wall.drag.dim.zero"] = "0 mm",
            ["wall.drag.dim.zero.nb"] = "0 mm",
            ["wall.drag.out"] = "out",
            ["wall.drag.out.nb"] = "ut",
            ["wall.drag.in"] = "in",
            ["wall.drag.in.nb"] = "inn",
            ["wall.drag.side.north"] = "North wall",
            ["wall.drag.side.north.nb"] = "Nordveggen",
            ["wall.drag.side.south"] = "South wall",
            ["wall.drag.side.south.nb"] = "Sørveggen",
            ["wall.drag.side.east"] = "East wall",
            ["wall.drag.side.east.nb"] = "Østveggen",
            ["wall.drag.side.west"] = "West wall",
            ["wall.drag.side.west.nb"] = "Vestveggen",
            ["wall.drag.receipt.outer"] = "{wall} moved {n} mm {way}",
            ["wall.drag.receipt.outer.nb"] = "{wall} flyttet {n} mm {way}",
            ["wall.drag.receipt.inner"] = "{wall} moved {n} mm {toward}",
            ["wall.drag.receipt.inner.nb"] = "{wall} flyttet {n} mm mot {toward}",
            ["wall.drag.followed.one"] = "; 1 wall followed",
            ["wall.drag.followed.one.nb"] = "; 1 vegg fulgte",
            ["wall.drag.followed"] = "; {n} walls followed",
            ["wall.drag.followed.nb"] = "; {n} vegger fulgte",
            ["wall.drag.pick"] = "Click the wall to drag.",
            ["wall.drag.pick.nb"] = "Klikk veggen som skal dras.",
            ["wall.drag.cancel"] = "Cancelled.",
            ["wall.drag.cancel.nb"] = "Avbrutt.",
            ["wall.drag"] = "Drag wall",
            ["wall.drag.nb"] = "Dra vegg",
            ["wall.drag.prompt"] = "Drag the wall in the view, or type a distance. Click or Enter places it. Esc cancels.",
            ["wall.drag.prompt.nb"] = "Dra veggen i visningen, eller skriv en avstand. Klikk eller Enter plasserer den. Esc avbryter.",
            ["wall.split"] = "Split walls for picking",
            ["wall.delete"] = "Delete",
            ["wall.delete.ask"] = "Which wall run goes? A click selects the whole wall record.",
            ["wall.delete.inner"] = "For an inner wall, say it: “delete the wall at 4000, 2500”.",
            ["exist.mark"] = "Treat this as the existing house?",
            ["wall.draw"] = "Draw wall",
            ["stair.draw"] = "Draw stair",
            ["stair.add"] = "Add stair",
            ["stair.edit"] = "Edit stair",
            ["stair.delete"] = "Delete stair",
            ["edit.undo"] = "Undo",
            ["ink.set"] = "Ink",
            ["meta.title"] = "Project info",
            ["meta.title.nb"] = "Prosjektinfo",
            ["bridge.start"] = "Start bridge",
            ["print.one"] = "Print one sheet",
            ["print.pages"] = "Choose sheets",
            ["export.dwg"] = "Export DWG",
            ["export.ifc"] = "Export IFC",
            ["export.csv"] = "Export CSV",
            ["export.csv.nb"] = "Eksporter CSV",
            ["detail.add"] = "Add detail",
            ["detail.add.nb"] = "Legg til detalj",
            ["detail.list"] = "Your details",
            ["detail.list.ask"] = "Details you added. Untick one and Save to remove it.",
            ["detail.plan"] = "plan",
            ["detail.elevation"] = "elevation",
            ["detail.section"] = "section",
            ["word.remove_all"] = "Remove all",
            ["takeoff"] = "Takeoff",
            ["print.clear"] = "Clear the layouts",
            ["sheets.clear"] = "Clear the sheet cache",
            ["rooms.list"] = "List rooms",
            ["area.stats"] = "Area summary",
            ["area.summary.note"] = "Estimate. Not measured to NS 3940.",

            // One-time cards: the question, then the pills.
            ["opening.type.ask"] = "Change to:",
            ["stair.edit.ask"] = "Stair sizes. The steps stay equal: their count follows the height.",
            ["stair.width"] = "Width",
            ["stair.riser_max"] = "Step height, at most",
            ["stair.going"] = "Going",
            ["stair.flip"] = "Flip",
            ["stair.same"] = "Nothing changed: the sizes are the same.",
            ["opening.type.all.ask"] = "Change all windows or all doors to:",
            ["opening.type.all.door"] = "Change all doors to:",
            ["opening.type.all.window"] = "Change all windows to:",
            ["file.check.ask"] = "What the import was not sure about",
            ["wall.review.ask"] = "What followed the wall",
            ["wall.review.ask.nb"] = "Hva som fulgte veggen",
            ["wall.review.longer"] = "{wall} · {mm} mm longer",
            ["wall.review.longer.nb"] = "{wall} · {mm} mm lengre",
            ["wall.review.shorter"] = "{wall} · {mm} mm shorter",
            ["wall.review.shorter.nb"] = "{wall} · {mm} mm kortere",
            ["wall.review.row"] = "{wall}",
            ["wall.review.row.nb"] = "{wall}",
            ["ink.set.ask"] = "Ink for the next Print. Sheets already drawn keep theirs until then.",
            ["ink.set.now"] = "Now: {ink}.",
            ["ink.default"] = "Default",
            ["ink.grey"] = "Grey",
            ["ink.hatch"] = "Hatch",
            ["meta.title.ask"] = "Project info for the title blocks.",
            ["meta.title.ask.nb"] = "Prosjektinfo til tegningshodene.",
            ["meta.title.first"] = "Project info for the title blocks. Asked once.",
            ["meta.title.first.nb"] = "Prosjektinfo til tegningshodene. Spørres én gang.",
            ["meta.save.print"] = "Save and print",
            ["meta.save.print.nb"] = "Lagre og skriv ut",
            ["meta.save.export"] = "Save and export",
            ["meta.save.export.nb"] = "Lagre og eksporter",
            ["meta.skip.print"] = "Print without",
            ["meta.skip.print.nb"] = "Skriv ut uten",
            ["meta.skip.export"] = "Export without",
            ["meta.skip.export.nb"] = "Eksporter uten",
            ["print.one.ask"] = "Which sheet?",
            ["print.pages.ask"] = "Sheets in the set",
            ["print.pages.scale"] = "Scale",
            ["print.pages.fit"] = "Scale picked to fit · A3",
            ["takeoff.ask"] = "Takeoff",
            ["takeoff.note"] = "Every figure is approx., from the model. Wall area is net of openings, one side.",
            ["sheet.section"] = "Section {letter}",
            ["print.clear.ask"] = "Clear the Forsk layouts and their drawings? The model stays.",
            ["sheets.clear.ask"] = "Clear the sheet cache on S-PLAN and S-ELEV? Print does not use it.",
            ["rooms.list.ask"] = "Rooms in this file",
            ["section.remove.ask"] = "Which section goes?",
            ["section.remove.all"] = "All sections",
            ["pdf.page.ask"] = "{file} has {n} pages. Which is the plan?",
            ["pdf.page.pill"] = "Page {n}",
            ["pdf.page.more"] = "Showing the first {n} pages.",
            ["word.done"] = "Done",
            ["word.save"] = "Save",
            ["word.print"] = "Print",
            ["word.reset"] = "Reset",

            // Words in a prefilled sentence.
            ["word.door"] = "door",
            ["word.window"] = "window",
            ["word.door.nb"] = "døra",
            ["word.window.nb"] = "vinduet",
            ["word.north"] = "North",
            ["word.south"] = "South",
            ["word.east"] = "East",
            ["word.west"] = "West",
            ["word.cancel"] = "Cancel",
            ["compass.north"] = "north",
            ["compass.north.nb"] = "nord",
            ["compass.south"] = "south",
            ["compass.south.nb"] = "sør",
            ["compass.east"] = "east",
            ["compass.east.nb"] = "øst",
            ["compass.west"] = "west",
            ["compass.west.nb"] = "vest",

            // The pick line (ForskPick): what is selected, in words.
            ["pick.none"] = "Click something in the model.",
            ["pick.none.nb"] = "Klikk noe i modellen.",
            ["pick.wall"] = "Wall {id}",
            ["pick.wall.nb"] = "Vegg {id}",
            ["pick.wall.at"] = "Wall at {at}",
            ["pick.wall.at.nb"] = "Vegg ved {at}",
            ["pick.wall.whole"] = "Wall {id} · {n} runs",
            ["pick.wall.whole.nb"] = "Vegg {id} · {n} deler",
            ["pick.room"] = "Room",
            ["pick.room.nb"] = "Rom",
            ["pick.door"] = "Door",
            ["pick.door.nb"] = "Dør",
            ["pick.window"] = "Window",
            ["pick.window.nb"] = "Vindu",
            ["pick.opening"] = "Opening",
            ["pick.opening.nb"] = "Åpning",
            ["pick.object"] = "1 object",
            ["pick.object.nb"] = "1 objekt",
            ["pick.walls"] = "{n} walls",
            ["pick.walls.nb"] = "{n} vegger",
            ["pick.rooms"] = "{n} rooms · {area}",
            ["pick.rooms.nb"] = "{n} rom · {area}",
            ["pick.doors"] = "{n} doors",
            ["pick.doors.nb"] = "{n} dører",
            ["pick.windows"] = "{n} windows",
            ["pick.windows.nb"] = "{n} vinduer",
            ["pick.openings"] = "{n} openings",
            ["pick.openings.nb"] = "{n} åpninger",
            ["pick.mix.wall"] = "1 wall",
            ["pick.mix.wall.nb"] = "1 vegg",
            ["pick.mix.door"] = "1 door",
            ["pick.mix.door.nb"] = "1 dør",
            ["pick.mix.window"] = "1 window",
            ["pick.mix.window.nb"] = "1 vindu",
            ["pick.mix.opening"] = "1 opening",
            ["pick.mix.opening.nb"] = "1 åpning",
            ["pick.stairs"] = "{n} stairs",
            ["pick.stairs.nb"] = "{n} trapper",
            ["pick.objects"] = "{n} objects",
            ["pick.objects.nb"] = "{n} objekter",

            // A viewport pick, mirrored as one line in the thread. Rhino takes the keyboard while it runs.
            ["prompt.scale"] = "Pick two points on a length you know, in the viewport. Esc cancels.",
            ["prompt.scale.length"] = "Real length between the two points",
            ["prompt.scale.set"] = "Set scale",
            ["prompt.section"] = "Pick the start of the section in the viewport, then its end. Esc cancels.",
            ["prompt.stair"] = "Click the foot of the stair in the plan, then where it ends. Type a length, or W for the width. Esc cancels.",
            ["prompt.wall"] = "Click the corners of the walls in the plan. Type a length and Enter, C closes, Enter finishes, Esc steps back. Shift turns the angle snap off.",
            ["prompt.draw"] = "Trace the walls in the viewport, on the wall layer. Enter finishes, Esc cancels.",

            // Lines in the thread.
            ["window.nofile"] = "No file open",
            ["line.reopened"] = "Reopened. The bar shows what is true for this file now.",
            ["line.busy"] = "Forsk is still working. Try again when the step line is gone.",
            ["line.thinking"] = "Thinking",
            ["line.generating"] = "Generating… step {i} of {n}",
            ["line.printing"] = "Printing… step {i} of {n}: {what}",
            ["line.running"] = "Running {what}…",
            ["line.bridge"] = "Bridge started.",
            ["line.printing.layout"] = "laying out the sheets",
            ["line.scale.cancelled"] = "Set scale cancelled.",
            ["line.scale.number"] = "Type the length in millimetres, such as 4000.",
            ["file.use_curves.done"] = "{n} curve(s) are on the wall layer now.",
            ["edit.undo.none"] = "Rhino had nothing to undo.",
            ["bridge.start.failed"] = "The bridge did not start: {why}",

            // Roles. One thread and one history; a role sharpens suggestions and tool choice.
            ["role.control"] = "Answer as",
            ["role.auto"] = "Auto",
            ["role.planner"] = "Planner",
            ["role.modeller"] = "Modeller",
            ["role.plotter"] = "Plotter",
            ["role.analyser"] = "Analyser",
            ["role.support"] = "Support",
            ["role.render"] = "Render",
            ["role.title"] = "Auto lets the router name the role for each answer. A pick stays until you choose Auto again.",
            ["support.ask"] = "Send this report?",
            ["support.send"] = "Send",
            ["support.sending"] = "Sending…",
            ["support.sending.nb"] = "Sender…",
            ["support.sent.short"] = "Sent",
            ["support.sent.short.nb"] = "Sendt",
            ["support.saved.short"] = "Saved",
            ["support.saved.short.nb"] = "Lagret",
            ["support.notsent"] = "Not sent",
            ["support.notsent.nb"] = "Ikke sendt",
            ["support.type"] = "Type",
            ["support.bug"] = "Bug",
            ["support.question"] = "Question",
            ["support.feature"] = "Feature request",
            ["support.description"] = "Description",
            ["support.email"] = "Email",
            ["support.attach"] = "Attach debug report",
            ["support.sent"] = "Sent. Reference {id} — we'll reply by email.",
            ["support.sent.nb"] = "Sendt. Referanse {id} — vi svarer på e-post.",
            ["support.sent.plain"] = "Sent. We'll reply by email.",
            ["support.sent.plain.nb"] = "Sendt. Vi svarer på e-post.",
            ["support.unavailable"] = "Couldn't reach Forsk support right now — your report is saved and will be sent later.",
            ["support.unavailable.nb"] = "Fikk ikke kontakt med Forsk support akkurat nå — rapporten er lagret og sendes senere.",
            ["support.later"] = "Support email isn't set up yet — your report is saved and will be sent later.",
            ["support.later.nb"] = "E-post til support er ikke satt opp ennå — rapporten er lagret og sendes senere.",
            ["support.failed"] = "The report didn't go through — it's saved and will be sent later.",
            ["support.failed.nb"] = "Rapporten kom ikke frem — den er lagret og sendes senere.",
            ["support.rate"] = "Too many reports just now — try again in {n} minutes.",
            ["support.rate.nb"] = "For mange rapporter akkurat nå — prøv igjen om {n} minutter.",
            ["support.rate.one"] = "Too many reports just now — try again in 1 minute.",
            ["support.rate.one.nb"] = "For mange rapporter akkurat nå — prøv igjen om 1 minutt.",
            ["support.rate.later"] = "Too many reports just now — try again in a few minutes.",
            ["support.rate.later.nb"] = "For mange rapporter akkurat nå — prøv igjen om noen minutter.",
            ["support.email.bad"] = "Type the email we should reply to.",
            ["support.email.bad.nb"] = "Skriv e-postadressen vi skal svare til.",
            ["support.message.missing"] = "Write what happened, then send.",
            ["support.message.missing.nb"] = "Skriv hva som skjedde, og send.",
            ["support.message.long"] = "That description is too long. Shorten it, then send.",
            ["support.message.long.nb"] = "Beskrivelsen er for lang. Korte den ned, og send.",
            ["support.type.bad"] = "Choose Bug, Question, or Feature request.",
            ["support.type.bad.nb"] = "Velg Bug, Question eller Feature request.",
            ["support.rejected"] = "That report couldn't be sent. Check it and try again.",
            ["support.rejected.nb"] = "Rapporten ble ikke sendt. Se over den og prøv igjen.",
            ["support.too_large"] = "That report is too large to send.",
            ["support.too_large.nb"] = "Rapporten er for stor til å sendes.",
            ["support.debug_large"] = "The debug report is too large. Untick it and send again.",
            ["support.debug_large.nb"] = "Feilsøkingsrapporten er for stor. Fjern haken og send på nytt.",

            // The bar.
            ["bar.because"] = "Suggested because",
            ["bar.help"] = "\u22ef",
            ["bar.refused"] = "{label} is no longer available here: the file changed.",

            // "What can I do here?" groups, in card order.
            ["group.start"] = "Start a project",
            ["group.import"] = "Import a plan",
            ["group.model"] = "Model and edit",
            ["group.openings"] = "Openings",
            ["group.rooms"] = "Rooms",
            ["group.print"] = "Print and sheets",
            ["group.daylight"] = "Daylight",
            ["group.sections"] = "Sections",
            ["group.profiles"] = "Ink",

            // One sentence where a neighbour would expect a dead control.
            ["hint.key"] = "Chat actions are hidden: Forsk has no API key. It reads FORSK_GROK_API_KEY, ~/.forsk/grok.env, or the repo .env.",
            ["hint.windows"] = "Daylight comes in through windows. Add a window, then run it.",
            ["hint.scale"] = "Generate waits for the scale: pick two points in the view, then type the real length.",
            ["hint.heights"] = "Generate uses the template heights. For other heights, say them: “generate with walls 2700”.",
            ["hint.units"] = "This file is not in millimetres. Forsk works in millimetres only.",

            // The one local sentence on an empty thread: it names the file state. No key needed.
            ["state.empty"] = "This file is empty.",
            ["state.foreign"] = "This file has geometry that Forsk did not make.",
            ["state.unscaled"] = "This file has an imported plan. Its scale is not confirmed.",
            ["state.plan"] = "This file has a 2D plan and no 3D model yet.",
            ["state.noplan"] = "This file has no plan yet.",
            ["state.partial"] = "This file has part of a Forsk model and no walls.",
            ["state.model"] = "This file has a Forsk 3D model.",
            ["state.units"] = "This file is not in millimetres. Switch the .3dm to millimetres, then Forsk can work on it.",

            // The status line.
            ["status.bridge"] = "Bridge off",
            ["status.ink"] = "ink: {ink}",

            // A step whose object is not named in its message.
            ["tool.clear_generated"] = "Model",
            ["tool.floor_from_layer"] = "Floor",
            ["tool.walls_from_layer"] = "Walls",
            ["tool.roof_flat_from_walls"] = "Roof",
            ["tool.openings_from_layer"] = "Openings",
            ["tool.rooms_from_layer"] = "Rooms",
            ["tool.rooms_detect"] = "Rooms",
            ["tool.rooms_set_type"] = "Room type",
            ["tool.rooms_colors"] = "Room colours",
            ["tool.mark_as_existing"] = "Existing house",
            ["tool.plan_import"] = "Plan",
            ["tool.plan_scale"] = "Scale",
            ["tool.dxf_import"] = "DXF",
            ["tool.layout_pack"] = "Sheets",
            ["tool.export_pdf"] = "PDF",
            ["tool.print_pages"] = "Sheets",
            ["tool.takeoff"] = "Takeoff",
            ["tool.clear_layouts"] = "Layouts",
            ["tool.clear_drawings"] = "Sheet cache",
            ["tool.sheet_pack"] = "Sheet cache",
            ["tool.make2d_view"] = "Sheet cache",
            ["tool.set_project_meta"] = "Title block",
            ["tool.print_profile"] = "Ink",
            ["tool.section_add"] = "Section",
            ["tool.section_clear"] = "Section",
            ["tool.section_pick"] = "Section",
            ["tool.daylight_from_model"] = "Daylight",
            ["tool.debug_report"] = "Debug report",
            ["tool.add_opening"] = "Opening",
            ["tool.move_opening"] = "Opening",
            ["tool.set_opening"] = "Opening",
            ["tool.set_opening_type"] = "Opening",
            ["tool.delete_opening"] = "Opening",
            ["tool.move_wall"] = "Wall",
            ["tool.delete_wall"] = "Wall",
            ["tool.add_wall"] = "Wall",
            ["tool.split_walls"] = "Wall",
            ["tool.room_push_pull"] = "Room",
            ["tool.add_stair"] = "Stair",
            ["tool.edit_stair"] = "Stair",
            ["tool.delete_stair"] = "Stair",
            ["receipt.ok"] = "done",
        };

        /// <summary>The string under a key. A missing key is a bug the registry tests catch; the key shows instead of a blank.</summary>
        public static string Get(string key)
        {
            return key != null && Strings.TryGetValue(key, out var text) ? text : key ?? "";
        }

        public static bool Has(string key)
        {
            return key != null && Strings.ContainsKey(key);
        }

        public static string Label(string actionId)
        {
            return Get(actionId);
        }

        /// <summary>A string with {name} slots filled.</summary>
        public static string Format(string key, params string[] pairs)
        {
            var text = Get(key);
            for (var i = 0; i + 1 < pairs.Length; i += 2)
                text = text.Replace("{" + pairs[i] + "}", pairs[i + 1] ?? "");
            return text;
        }

        public static IEnumerable<string> Keys => Strings.Keys;
    }
}
